name = "TestOmnizart"
uuid = "589bba42-b518-4049-99db-0870857c7954"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"
Jive = "0.3"
MIDI = "2.7"
IterTools = "1.10"
MusicManipulations = "1.7"
Statistics = "1.11"
Unitful = "1.22"
TimeUnits = "0.1"
Graphs = "1.12"
GraphsMatching = "0.2"
JuMP = "1.26"
Cbc = "1.2"
BlossomV = "0.4"
Bach = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
MIDI = "f57c4921-e30c-5f49-b073-3f2f2ada663e"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
MusicManipulations = "274955c0-c284-5bf7-b122-5ecd51c559de"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
TimeUnits = "06db76f2-042d-446b-9347-171e0bf2444a"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphsMatching = "c3af3a8c-b79e-4b01-bf44-c718d7e0e0d6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
BlossomV = "6c721016-9dae-5d90-abf6-67daaccb2332"
Bach = "c92c169f-a3eb-4915-8049-070c90b52b43"

[targets]
test = ["Test", "Jive", "MIDI", "IterTools", "MusicManipulations", "Statistics", "Unitful", "TimeUnits", "Graphs", "GraphsMatching", "JuMP", "Cbc", "BlossomV", "Bach"]

[sources]
Bach = {url = "https://github.com/wookay/Bach.jl", rev = "main"}
TimeUnits = {url = "https://github.com/wookay/TimeUnits.jl", rev = "main"}
